todolist/accounts/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^login/$', views.home, name='home'),
    url(r'^cadastro/$', views.register, name='register'),
    url(r'^fazer-login/$', views.user_login, name='user-login'),
    url(r'^logado/$', views.logado, name='logado'),
    url(r'^sair/$', views.sair, name='sair'),
]

todolist/urls.py
from django.conf.urls import url, include
from django.contrib import admin
#Servir assets em desenvolvimento
from django.conf import settings
from django.conf.urls.static import static

from todolist.accounts import urls as accounts_urls

urlpatterns = [
    url(r'', include(accounts_urls, namespace='accounts')),
    url(r'^admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

todolist/accounts/models.py
from django.db import models

# Create your models here.

todolist/core/models.py
from django.db import models

# Create your models here.

todolist/tasks/models.py
from django.db import models

# Create your models here.

todolist/accounts/forms.py
from django import forms
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    # first_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    # last_name = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    # email = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    # username = forms.CharField(widget=forms.TextInput(attrs={"class": "form-control"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "form-control"}))
    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email', 'username', 'password', 'user_permissions')

    def clean_first_name(self):
        first_name = self.cleaned_data['first_name']
        if first_name == '':
            raise forms.ValidationError('Este campo é obrigatório')
        return first_name

    def clean_last_name(self):
        last_name = self.cleaned_data['last_name']
        if last_name == '':
            raise forms.ValidationError('Este campo e obrigatorio')
        return last_name

    def clean_email(self):
        email = self.cleaned_data['email']
        if email == '':
            raise forms.ValidationError('Este campo e obrigatorio')
        if User.objects.filter(email=email).exists():
            raise forms.ValidationError('Email já existente.')
        return email

todolist/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib import messages

from .forms import UserForm

# Create your views here.

def home(request):
    return render(request, 'accounts/user_login.html')

def register(request):
    if request.method == 'POST':
        form = UserForm(request.POST)
        if form.is_valid():
            f = form.save(commit=False)
            f.set_password('password')
            f.save()
            return redirect('accounts:home')
        else:
            print(form.errors)
    else:
        form = UserForm()
    return render(request, 'accounts/register.html', {'form': form})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return redirect('accounts:logado')
			else:
				messages.debug(request, 'Sua conta está desativada.')
				return render(request, 'accounts/user_login.html')
		else:
			print('Login inválido, detalhes: {0}, {1}'.format(username, password))
			messages.error(request, 'Usuário ou senha inválido.')
			return render(request, 'accounts/user_login.html')
	else:
		return render(request, 'accounts/user_login.html', {})

@login_required
def logado(request):
    return render(request, 'accounts/logado.html')

@login_required
def sair(request):
    logout(request)
    return redirect('accounts:home')

todolist/core/views.py
from django.shortcuts import render

# Create your views here.

todolist/tasks/views.py
from django.shortcuts import render

# Create your views here.

todolist/accounts/templates/accounts/logado.html
{% extends "base.html" %}

{% block body %}
  <h1>Passei!!!</h1>
  {{ user }}
{% endblock body %}

todolist/accounts/templates/accounts/register.html
{% extends "base.html" %}

{% load widget_tweaks %}

{% block title %}
  Cadastro de novo usuário | {{ block.super }}
{% endblock title %}

{% block body %}

  <form class="" action="" method="post">
    {% csrf_token %}
    <div class="form-group">
      <label for="{{ form.first_name.id_for_label }}">Nome</label>
      {{ form.first_name|add_class:"form-control" }}
    </div>
    {% if form.first_name.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.first_name.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.last_name.id_for_label }}">Sobrenome</label>
      {{ form.last_name|add_class:"form-control" }}
    </div>
    {% if form.last_name.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.last_name.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.email.id_for_label }}">Email</label>
      {{ form.email|add_class:"form-control" }}
    </div>
    {% if form.email.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.email.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.username.id_for_label }}">Usuário</label>
      {{ form.username|add_class:"form-control" }}
    </div>
    {% if form.username.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.username.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.password.id_for_label }}">Senha</label>
      {{ form.password|add_class:"form-control" }}
    </div>
    {% if form.password.errors %}
      <div class="alert alert-danger" role="alert">
        {{ form.password.errors }}
      </div>
    {% endif %}
    <div class="form-group">
      <label for="{{ form.user_permissions.id_for_label }}">Permissões</label>
      {{ form.user_permissions|add_class:"form-control" }}
    </div>
    <div class="form-group">
      <button type="submit" class="btn btn-primary">Cadastrar</button>
    </div>

  </form>

{% endblock body %}

todolist/accounts/templates/accounts/user_login.html
{% extends "base.html" %}

{% block title %}
  Fazer login | {{ block.super }}
{% endblock title %}

{% block body %}

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-warning">
        {{ message }}
      </div>
    {% endfor %}
  {% endif %}

  <form method="post" action="{% url 'accounts:user-login' %}">

    {% csrf_token %}

    <div class="form-group">
      <label for="username">Nome de usuário</label>
      <input type="text" class="form-control" id="username" name="username" placeholder="Digite seu usuário">
    </div>
    <div class="form-group">
      <label for="password">Informe sua senha</label>
      <input type="password" class="form-control" id="password" name="password" placeholder="Digite sua senha">
    </div>
    <div class="form-group">
      <a href="{% url 'accounts:register' %}">Não tem cadastro? Faça aqui.</a>
    </div>
    <button type="submit" class="btn btn-default">Entrar</button>
  </form>

{% endblock body %}

todolist/core/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <title>{% block title %}Sistema de Gerenciamento de Tarefas{% endblock title %}</title>

    <!-- Bootstrap -->
    <link href="{% static "css/bootstrap.min.css" %}" rel="stylesheet">

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>
  <body>
    <nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">ToDo List</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li class="active"><a href="/">Login <span class="sr-only">(current)</span></a></li>
        <li><a href="{% url 'accounts:register' %}">Cadastre-se</a></li>

      </ul>
      {% if user.is_authenticated %}
        <form class="navbar-form navbar-left">
          <div class="form-group">
            <input type="text" class="form-control" placeholder="Digite sua busca">
          </div>
          <button type="submit" class="btn btn-default">Pesquisar</button>
        </form>
      {% endif %}
      {% if user.is_authenticated %}
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Francisco André <span class="caret"></span></a>
            <ul class="dropdown-menu">
              <li><a href="#">Perfil</a></li>
              <li role="separator" class="divider"></li>
              <li><a href="{% url 'accounts:sair' %}">Sair</a></li>
            </ul>
          </li>
        </ul>
      {% endif %}
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
  <div class="container">
    {% block body %}
    {% endblock body %}
  </div>
    <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <!-- Include all compiled plugins (below), or include individual files as needed -->
    <script src="{% static "js/bootstrap.min.js" %}"></script>
    <!--<script src="{% static "js/todo.js" %}"></script>-->
  </body>
</html>